### ISSUE TITLE
'Duplicate stream for peer' exceptions

### ISSUE THREAD

**Issue by Nashatyrev** [libp2p/jvm-libp2p#122]
Got the series of exceptions. There are two kinds of them and they are most likely related: 

```
2020-07-13 05:14:23.654+03:00 | P2PService-event-thread-0 | WARN  | AbstractRouter | P2PService internal error on message null from peer null
io.libp2p.core.BadPeerException: Duplicate steam for peer 16Uiu2HAmGrmArgsbrgQ8rPygdZknQ7jqUW5Wgs2LQQVq9aEqPaZN. Closing it silently
	at io.libp2p.etc.util.P2PServiceSemiDuplex.streamAdded(P2PServiceSemiDuplex.kt:40) ~[jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at io.libp2p.etc.util.P2PService$StreamHandler$handlerAdded$1.invoke(P2PService.kt:43) ~[jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at io.libp2p.etc.util.P2PService$StreamHandler$handlerAdded$1.invoke(P2PService.kt:36) ~[jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at io.libp2p.etc.util.P2PService$runOnEventThread$1.run(P2PService.kt:220) [jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
2020-07-13 05:14:23.655+03:00 | P2PService-event-thread-0 | WARN  | AbstractRouter | P2PService internal error on message null from peer null
io.libp2p.core.InternalErrorException: [peerHandler] not initialized yet
	at io.libp2p.etc.util.P2PService$StreamHandler.getPeerHandler(P2PService.kt:81) ~[jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at io.libp2p.etc.util.P2PServiceSemiDuplex.streamActive(P2PServiceSemiDuplex.kt:55) ~[jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at io.libp2p.etc.util.P2PService$StreamHandler$channelActive$1.invoke(P2PService.kt:60) ~[jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at io.libp2p.etc.util.P2PService$StreamHandler$channelActive$1.invoke(P2PService.kt:36) ~[jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at io.libp2p.etc.util.P2PService$runOnEventThread$1.run(P2PService.kt:220) [jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
2020-07-13 05:14:23.655+03:00 | P2PService-event-thread-0 | WARN  | AbstractRouter | P2PService internal error on message null from peer null
io.libp2p.core.InternalErrorException: [peerHandler] not initialized yet
	at io.libp2p.etc.util.P2PService$StreamHandler.getPeerHandler(P2PService.kt:81) ~[jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at io.libp2p.etc.util.P2PService.streamDisconnected(P2PService.kt:149) [jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at io.libp2p.etc.util.P2PService$StreamHandler$channelUnregistered$1.invoke(P2PService.kt:67) ~[jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at io.libp2p.etc.util.P2PService$StreamHandler$channelUnregistered$1.invoke(P2PService.kt:36) ~[jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at io.libp2p.etc.util.P2PService$runOnEventThread$1.run(P2PService.kt:220) [jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
2020-07-13 05:14:25.209+03:00 | P2PService-event-thread-0 | WARN  | AbstractRouter | P2PService internal error on message null from peer null
io.libp2p.core.BadPeerException: Duplicate steam for peer 16Uiu2HAmGrmArgsbrgQ8rPygdZknQ7jqUW5Wgs2LQQVq9aEqPaZN. Closing it silently
	at io.libp2p.etc.util.P2PServiceSemiDuplex.streamAdded(P2PServiceSemiDuplex.kt:40) ~[jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at io.libp2p.etc.util.P2PService$StreamHandler$handlerAdded$1.invoke(P2PService.kt:43) ~[jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at io.libp2p.etc.util.P2PService$StreamHandler$handlerAdded$1.invoke(P2PService.kt:36) ~[jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at io.libp2p.etc.util.P2PService$runOnEventThread$1.run(P2PService.kt:220) [jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
2020-07-13 05:14:25.209+03:00 | P2PService-event-thread-0 | WARN  | AbstractRouter | P2PService internal error on message null from peer null
io.libp2p.core.InternalErrorException: [peerHandler] not initialized yet
	at io.libp2p.etc.util.P2PService$StreamHandler.getPeerHandler(P2PService.kt:81) ~[jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at io.libp2p.etc.util.P2PServiceSemiDuplex.streamActive(P2PServiceSemiDuplex.kt:55) ~[jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at io.libp2p.etc.util.P2PService$StreamHandler$channelActive$1.invoke(P2PService.kt:60) ~[jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at io.libp2p.etc.util.P2PService$StreamHandler$channelActive$1.invoke(P2PService.kt:36) ~[jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at io.libp2p.etc.util.P2PService$runOnEventThread$1.run(P2PService.kt:220) [jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
2020-07-13 05:14:25.210+03:00 | P2PService-event-thread-0 | WARN  | AbstractRouter | P2PService internal error on message null from peer null
io.libp2p.core.InternalErrorException: [peerHandler] not initialized yet
	at io.libp2p.etc.util.P2PService$StreamHandler.getPeerHandler(P2PService.kt:81) ~[jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at io.libp2p.etc.util.P2PService.streamDisconnected(P2PService.kt:149) [jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at io.libp2p.etc.util.P2PService$StreamHandler$channelUnregistered$1.invoke(P2PService.kt:67) ~[jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at io.libp2p.etc.util.P2PService$StreamHandler$channelUnregistered$1.invoke(P2PService.kt:36) ~[jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at io.libp2p.etc.util.P2PService$runOnEventThread$1.run(P2PService.kt:220) [jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
2020-07-13 05:14:30.617+03:00 | P2PService-event-thread-0 | WARN  | AbstractRouter | P2PService internal error on message null from peer null
io.libp2p.core.BadPeerException: Duplicate steam for peer 16Uiu2HAmGrmArgsbrgQ8rPygdZknQ7jqUW5Wgs2LQQVq9aEqPaZN. Closing it silently
	at io.libp2p.etc.util.P2PServiceSemiDuplex.streamAdded(P2PServiceSemiDuplex.kt:40) ~[jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at io.libp2p.etc.util.P2PService$StreamHandler$handlerAdded$1.invoke(P2PService.kt:43) ~[jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at io.libp2p.etc.util.P2PService$StreamHandler$handlerAdded$1.invoke(P2PService.kt:36) ~[jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at io.libp2p.etc.util.P2PService$runOnEventThread$1.run(P2PService.kt:220) [jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
2020-07-13 05:14:30.618+03:00 | P2PService-event-thread-0 | WARN  | AbstractRouter | P2PService internal error on message null from peer null
io.libp2p.core.InternalErrorException: [peerHandler] not initialized yet
	at io.libp2p.etc.util.P2PService$StreamHandler.getPeerHandler(P2PService.kt:81) ~[jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at io.libp2p.etc.util.P2PServiceSemiDuplex.streamActive(P2PServiceSemiDuplex.kt:55) ~[jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at io.libp2p.etc.util.P2PService$StreamHandler$channelActive$1.invoke(P2PService.kt:60) ~[jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at io.libp2p.etc.util.P2PService$StreamHandler$channelActive$1.invoke(P2PService.kt:36) ~[jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at io.libp2p.etc.util.P2PService$runOnEventThread$1.run(P2PService.kt:220) [jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
2020-07-13 05:14:30.618+03:00 | P2PService-event-thread-0 | WARN  | AbstractRouter | P2PService internal error on message null from peer null
io.libp2p.core.InternalErrorException: [peerHandler] not initialized yet
	at io.libp2p.etc.util.P2PService$StreamHandler.getPeerHandler(P2PService.kt:81) ~[jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at io.libp2p.etc.util.P2PService.streamDisconnected(P2PService.kt:149) [jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at io.libp2p.etc.util.P2PService$StreamHandler$channelUnregistered$1.invoke(P2PService.kt:67) ~[jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at io.libp2p.etc.util.P2PService$StreamHandler$channelUnregistered$1.invoke(P2PService.kt:36) ~[jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at io.libp2p.etc.util.P2PService$runOnEventThread$1.run(P2PService.kt:220) [jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
2020-07-13 05:14:33.266+03:00 | TimeTickChannel-0 | INFO  | teku-event-log | [37mSlot Event  *** Slot: 97722, Block: 7aaa16..70db, Epoch: 3053, Finalized checkpoint: 3050, Finalized root: be0853..9ef0, Peers: 72[0m
2020-07-13 05:14:42.540+03:00 | P2PService-event-thread-0 | WARN  | AbstractRouter | P2PService internal error on message null from peer null
io.libp2p.core.BadPeerException: Duplicate steam for peer 16Uiu2HAmGrmArgsbrgQ8rPygdZknQ7jqUW5Wgs2LQQVq9aEqPaZN. Closing it silently
	at io.libp2p.etc.util.P2PServiceSemiDuplex.streamAdded(P2PServiceSemiDuplex.kt:40) ~[jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at io.libp2p.etc.util.P2PService$StreamHandler$handlerAdded$1.invoke(P2PService.kt:43) ~[jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at io.libp2p.etc.util.P2PService$StreamHandler$handlerAdded$1.invoke(P2PService.kt:36) ~[jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at io.libp2p.etc.util.P2PService$runOnEventThread$1.run(P2PService.kt:220) [jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
2020-07-13 05:14:42.540+03:00 | P2PService-event-thread-0 | WARN  | AbstractRouter | P2PService internal error on message null from peer null
io.libp2p.core.InternalErrorException: [peerHandler] not initialized yet
	at io.libp2p.etc.util.P2PService$StreamHandler.getPeerHandler(P2PService.kt:81) ~[jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at io.libp2p.etc.util.P2PServiceSemiDuplex.streamActive(P2PServiceSemiDuplex.kt:55) ~[jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at io.libp2p.etc.util.P2PService$StreamHandler$channelActive$1.invoke(P2PService.kt:60) ~[jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at io.libp2p.etc.util.P2PService$StreamHandler$channelActive$1.invoke(P2PService.kt:36) ~[jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at io.libp2p.etc.util.P2PService$runOnEventThread$1.run(P2PService.kt:220) [jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
2020-07-13 05:14:42.540+03:00 | P2PService-event-thread-0 | WARN  | AbstractRouter | P2PService internal error on message null from peer null
io.libp2p.core.InternalErrorException: [peerHandler] not initialized yet
	at io.libp2p.etc.util.P2PService$StreamHandler.getPeerHandler(P2PService.kt:81) ~[jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at io.libp2p.etc.util.P2PService.streamDisconnected(P2PService.kt:149) [jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at io.libp2p.etc.util.P2PService$StreamHandler$channelUnregistered$1.invoke(P2PService.kt:67) ~[jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at io.libp2p.etc.util.P2PService$StreamHandler$channelUnregistered$1.invoke(P2PService.kt:36) ~[jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at io.libp2p.etc.util.P2PService$runOnEventThread$1.run(P2PService.kt:220) [jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
2020-07-13 05:14:45.265+03:00 | TimeTickChannel-0 | INFO  | teku-event-log | [37mSlot Event  *** Slot: 97723, Block:    ... empty, Epoch: 3053, Finalized checkpoint: 3050, Finalized root: be0853..9ef0, Peers: 72[0m
2020-07-13 05:14:53.171+03:00 | P2PService-event-thread-0 | WARN  | AbstractRouter | P2PService internal error on message null from peer null
io.libp2p.core.BadPeerException: Duplicate steam for peer 16Uiu2HAmGrmArgsbrgQ8rPygdZknQ7jqUW5Wgs2LQQVq9aEqPaZN. Closing it silently
	at io.libp2p.etc.util.P2PServiceSemiDuplex.streamAdded(P2PServiceSemiDuplex.kt:40) ~[jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at io.libp2p.etc.util.P2PService$StreamHandler$handlerAdded$1.invoke(P2PService.kt:43) ~[jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at io.libp2p.etc.util.P2PService$StreamHandler$handlerAdded$1.invoke(P2PService.kt:36) ~[jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at io.libp2p.etc.util.P2PService$runOnEventThread$1.run(P2PService.kt:220) [jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
2020-07-13 05:14:53.172+03:00 | P2PService-event-thread-0 | WARN  | AbstractRouter | P2PService internal error on message null from peer null
io.libp2p.core.InternalErrorException: [peerHandler] not initialized yet
	at io.libp2p.etc.util.P2PService$StreamHandler.getPeerHandler(P2PService.kt:81) ~[jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at io.libp2p.etc.util.P2PServiceSemiDuplex.streamActive(P2PServiceSemiDuplex.kt:55) ~[jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at io.libp2p.etc.util.P2PService$StreamHandler$channelActive$1.invoke(P2PService.kt:60) ~[jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at io.libp2p.etc.util.P2PService$StreamHandler$channelActive$1.invoke(P2PService.kt:36) ~[jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at io.libp2p.etc.util.P2PService$runOnEventThread$1.run(P2PService.kt:220) [jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
2020-07-13 05:14:53.172+03:00 | P2PService-event-thread-0 | WARN  | AbstractRouter | P2PService internal error on message null from peer null
io.libp2p.core.InternalErrorException: [peerHandler] not initialized yet
	at io.libp2p.etc.util.P2PService$StreamHandler.getPeerHandler(P2PService.kt:81) ~[jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at io.libp2p.etc.util.P2PService.streamDisconnected(P2PService.kt:149) [jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at io.libp2p.etc.util.P2PService$StreamHandler$channelUnregistered$1.invoke(P2PService.kt:67) ~[jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at io.libp2p.etc.util.P2PService$StreamHandler$channelUnregistered$1.invoke(P2PService.kt:36) ~[jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at io.libp2p.etc.util.P2PService$runOnEventThread$1.run(P2PService.kt:220) [jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

**Comment by Nashatyrev** [comment]
Reproduced this by doing the second test connection between two `GossipRouter`s
