### ISSUE TITLE
Not support Java8 Runtime, Version: 0.7.0-RELEASE

### ISSUE THREAD

**Issue by dvbug** [libp2p/jvm-libp2p#214]
Hi guys,

This project does not support Java8 Runtime,(Java11 works fine )
The reason may be related to proto buff generated class

- some files generated by pb, like: crypto.pb.Crypto.class

my dependency:
```xml
<dependency>
    <groupId>io.libp2p</groupId>
    <artifactId>jvm-libp2p-minimal</artifactId>
    <version>0.7.0-RELEASE</version>
</dependency>
```

It can not be compiled succeed, if I used Java8.
```console
[ERROR] /xxxxxxx.A.java:[14,26] Unable to access io.libp2p.core .dsl.HostBuilder
   Bad class file: /home/vito/.m2/repository/io/libp2p/jvm-libp2p-minimal/0.7.0-RELEASE/jvm-libp2p-minimal-0.7.0-RELEASE.jar(io/libp2p/core /dsl/HostBuilder.class)
     Class file has wrong version 55.0, should be 52.0
     Please delete this file or make sure it is in the correct classpath subdirectory.
[INFO] 1 error
```

It can be compiled succeed when I copied HostBuilder.java code into my project, but raised error on running.

see the trace log below, may be related to the code generated by pb

---

Java8 Runtime Trace

```console
Exception in thread "main" java.lang.UnsupportedClassVersionError: crypto/pb/Crypto$KeyType has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at io.libp2p.core.crypto.KeyKt$WhenMappings.<clinit>(Unknown Source)
	at io.libp2p.core.crypto.KeyKt.generateKeyPair(Key.kt:120)
	at io.libp2p.core.crypto.KeyKt.generateKeyPair$default(Key.kt:119)
	at io.libp2p.core.dsl.IdentityBuilder$random$$inlined$apply$lambda$1.invoke(Builders.kt:221)
	at io.libp2p.core.dsl.IdentityBuilder$random$$inlined$apply$lambda$1.invoke(Builders.kt:217)
	at io.libp2p.core.dsl.Builder.build(Builders.kt:161)
	at io.libp2p.core.dsl.BuilderJKt.hostJ(BuilderJ.kt:15)
	at io.libp2p.core.dsl.HostBuilder.build(HostBuilder.java:74)
        ...

```

**Comment by ajsutton** [comment]
The 0.7.0 release is very old, could you try with the latest 0.8.7 release? I just compiled it with only java 8 available so it should work.

**Comment by ajsutton** [comment]
Closing for lack of input. Will be dropping Java 8 support in the next release anyway.
