### ISSUE TITLE
Build fails on aarch64

### ISSUE THREAD

**Issue by jtraglia** [libp2p/jvm-libp2p#220]
Building fails on aarch64 systems (Linux & macOS).

```
jtraglia@ubuntu:~/git/jvm-libp2p$ uname -a
Linux ubuntu 5.4.0-99-generic #112-Ubuntu SMP Wed Feb 2 17:13:12 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
```

Specifically, these two tests failed which causes the build to fail:

```
TcpTransportTest > dial then close server transport() FAILED
    org.opentest4j.AssertionFailedError: Connections not acknowledged by server ==> expected: <50> but was: <40>
```

```
TcpTransportTest > dial then close client transport() FAILED
    org.opentest4j.AssertionFailedError: Connections not acknowledged by server ==> expected: <50> but was: <46>
```

<details closed>
<summary>Build Output</summary>

```
jtraglia@ubuntu:~/git/jvm-libp2p$ ./gradlew build
Starting a Gradle Daemon, 1 busy Daemon could not be reused, use --status for details

> Task :compileKotlin
w: Language version 1.4 is deprecated and its support will be removed in a future version of Kotlin
w: /home/jtraglia/git/jvm-libp2p/src/main/kotlin/io/libp2p/core/P2PChannelHandler.kt: (19, 6): 'JvmDefault' is deprecated. Switch to new -Xjvm-default modes: `all` or `all-compatibility`
w: /home/jtraglia/git/jvm-libp2p/src/main/kotlin/io/libp2p/core/P2PChannelHandler.kt: (27, 6): 'JvmDefault' is deprecated. Switch to new -Xjvm-default modes: `all` or `all-compatibility`
w: /home/jtraglia/git/jvm-libp2p/src/main/kotlin/io/libp2p/core/P2PChannelHandler.kt: (29, 18): Unchecked cast: P2PChannel to TChannel
w: /home/jtraglia/git/jvm-libp2p/src/main/kotlin/io/libp2p/core/multistream/ProtocolBinding.kt: (30, 6): 'JvmDefault' is deprecated. Switch to new -Xjvm-default modes: `all` or `all-compatibility`
w: /home/jtraglia/git/jvm-libp2p/src/main/kotlin/io/libp2p/core/multistream/ProtocolBinding.kt: (37, 6): 'JvmDefault' is deprecated. Switch to new -Xjvm-default modes: `all` or `all-compatibility`
w: /home/jtraglia/git/jvm-libp2p/src/main/kotlin/io/libp2p/core/multistream/ProtocolBinding.kt: (56, 6): 'JvmDefault' is deprecated. Switch to new -Xjvm-default modes: `all` or `all-compatibility`
w: /home/jtraglia/git/jvm-libp2p/src/main/kotlin/io/libp2p/core/mux/StreamMuxer.kt: (43, 10): 'JvmDefault' is deprecated. Switch to new -Xjvm-default modes: `all` or `all-compatibility`
w: /home/jtraglia/git/jvm-libp2p/src/main/kotlin/io/libp2p/host/HostImpl.kt: (98, 83): Unchecked cast: ProtocolBinding<Any>? to ProtocolBinding<TController>
w: /home/jtraglia/git/jvm-libp2p/src/main/kotlin/io/libp2p/pubsub/PubsubRouter.kt: (25, 6): 'JvmDefault' is deprecated. Switch to new -Xjvm-default modes: `all` or `all-compatibility`
w: /home/jtraglia/git/jvm-libp2p/src/main/kotlin/io/libp2p/pubsub/TopicSubscriptionFilter.kt: (7, 6): 'JvmDefault' is deprecated. Switch to new -Xjvm-default modes: `all` or `all-compatibility`
w: /home/jtraglia/git/jvm-libp2p/src/main/kotlin/io/libp2p/pubsub/gossip/GossipScore.kt: (227, 29): Parameter 'peer' is never used
w: /home/jtraglia/git/jvm-libp2p/src/main/kotlin/io/libp2p/pubsub/gossip/GossipScore.kt: (227, 59): Parameter 'msg' is never used

> Task :compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :compileTestKotlin
w: /home/jtraglia/git/jvm-libp2p/src/test/kotlin/io/libp2p/core/HostTest.kt: (239, 25): Unchecked cast: Any to TMessage
w: /home/jtraglia/git/jvm-libp2p/src/test/kotlin/io/libp2p/core/HostTest.kt: (246, 25): Unchecked cast: Any to TMessage
w: /home/jtraglia/git/jvm-libp2p/src/test/kotlin/io/libp2p/core/HostTest.kt: (265, 28): The corresponding parameter in the supertype 'ChannelVisitor' is named 'channel'. This may cause problems when calling this function with named arguments.
w: /home/jtraglia/git/jvm-libp2p/src/test/kotlin/io/libp2p/core/multiformats/MultihashTest.kt: (116, 45): 'toUpperCase(): String' is deprecated. Use uppercase() instead.
w: /home/jtraglia/git/jvm-libp2p/src/test/kotlin/io/libp2p/pubsub/PubsubRouterTest.kt: (224, 39): 'sumBy((T) -> Int): Int' is deprecated. Use sumOf instead.
w: /home/jtraglia/git/jvm-libp2p/src/test/kotlin/io/libp2p/pubsub/PubsubRouterTest.kt: (260, 43): 'sumBy((T) -> Int): Int' is deprecated. Use sumOf instead.
w: /home/jtraglia/git/jvm-libp2p/src/test/kotlin/io/libp2p/pubsub/PubsubRouterTest.kt: (261, 47): 'sumBy((T) -> Int): Int' is deprecated. Use sumOf instead.
w: /home/jtraglia/git/jvm-libp2p/src/test/kotlin/io/libp2p/pubsub/PubsubRouterTest.kt: (276, 43): 'sumBy((T) -> Int): Int' is deprecated. Use sumOf instead.
w: /home/jtraglia/git/jvm-libp2p/src/test/kotlin/io/libp2p/pubsub/PubsubRouterTest.kt: (277, 47): 'sumBy((T) -> Int): Int' is deprecated. Use sumOf instead.
w: /home/jtraglia/git/jvm-libp2p/src/test/kotlin/io/libp2p/pubsub/PubsubRouterTest.kt: (327, 43): 'sumBy((T) -> Int): Int' is deprecated. Use sumOf instead.
w: /home/jtraglia/git/jvm-libp2p/src/test/kotlin/io/libp2p/pubsub/PubsubRouterTest.kt: (328, 41): 'sumBy((T) -> Int): Int' is deprecated. Use sumOf instead.
w: /home/jtraglia/git/jvm-libp2p/src/test/kotlin/io/libp2p/pubsub/PubsubRouterTest.kt: (344, 43): 'sumBy((T) -> Int): Int' is deprecated. Use sumOf instead.
w: /home/jtraglia/git/jvm-libp2p/src/test/kotlin/io/libp2p/pubsub/PubsubRouterTest.kt: (345, 47): 'sumBy((T) -> Int): Int' is deprecated. Use sumOf instead.
w: /home/jtraglia/git/jvm-libp2p/src/test/kotlin/io/libp2p/pubsub/gossip/GossipPubsubRouterTest.kt: (79, 40): 'sumBy((T) -> Int): Int' is deprecated. Use sumOf instead.
w: /home/jtraglia/git/jvm-libp2p/src/test/kotlin/io/libp2p/pubsub/gossip/GossipPubsubRouterTest.kt: (89, 40): 'sumBy((T) -> Int): Int' is deprecated. Use sumOf instead.
w: /home/jtraglia/git/jvm-libp2p/src/test/kotlin/io/libp2p/pubsub/gossip/GossipPubsubRouterTest.kt: (105, 40): 'sumBy((T) -> Int): Int' is deprecated. Use sumOf instead.
w: /home/jtraglia/git/jvm-libp2p/src/test/kotlin/io/libp2p/pubsub/gossip/GossipV1_1Tests.kt: (55, 15): 'open' has no effect in a final class
w: /home/jtraglia/git/jvm-libp2p/src/test/kotlin/io/libp2p/pubsub/gossip/GossipV1_1Tests.kt: (71, 24): Parameter 'outbound' is never used
w: /home/jtraglia/git/jvm-libp2p/src/test/kotlin/io/libp2p/pubsub/gossip/GossipV1_1Tests.kt: (352, 13): Variable 'connection' is never used
w: /home/jtraglia/git/jvm-libp2p/src/test/kotlin/io/libp2p/tools/NullHost.kt: (42, 35): The corresponding parameter in the supertype 'Host' is named 'streamVisitor'. This may cause problems when calling this function with named arguments.
w: /home/jtraglia/git/jvm-libp2p/src/test/kotlin/io/libp2p/tools/NullHost.kt: (46, 38): The corresponding parameter in the supertype 'Host' is named 'streamVisitor'. This may cause problems when calling this function with named arguments.
w: /home/jtraglia/git/jvm-libp2p/src/test/kotlin/io/libp2p/tools/TestChannel.kt: (89, 42): Elvis operator (?:) always returns the left operand of non-nullable type String
w: /home/jtraglia/git/jvm-libp2p/src/test/kotlin/io/libp2p/tools/TestLogAppender.kt: (10, 25): 'constructor AbstractAppender(String!, Filter!, Layout<out Serializable!>!)' is deprecated. Deprecated in Java
w: /home/jtraglia/git/jvm-libp2p/src/test/kotlin/io/libp2p/tools/protobuf/ProtobufUtils.kt: (28, 33): 'toByte(): Byte' is deprecated. Conversion of Char to Number is deprecated. Use Char.code property instead.
w: /home/jtraglia/git/jvm-libp2p/src/test/kotlin/io/libp2p/tools/protobuf/ProtobufUtils.kt: (30, 33): 'toByte(): Byte' is deprecated. Conversion of Char to Number is deprecated. Use Char.code property instead.
w: /home/jtraglia/git/jvm-libp2p/src/test/kotlin/io/libp2p/tools/protobuf/ProtobufUtils.kt: (31, 33): 'toByte(): Byte' is deprecated. Conversion of Char to Number is deprecated. Use Char.code property instead.
w: /home/jtraglia/git/jvm-libp2p/src/test/kotlin/io/libp2p/tools/protobuf/ProtobufUtils.kt: (32, 33): 'toByte(): Byte' is deprecated. Conversion of Char to Number is deprecated. Use Char.code property instead.
w: /home/jtraglia/git/jvm-libp2p/src/test/kotlin/io/libp2p/tools/protobuf/ProtobufUtils.kt: (34, 34): 'toByte(): Byte' is deprecated. Conversion of Char to Number is deprecated. Use Char.code property instead.
w: /home/jtraglia/git/jvm-libp2p/src/test/kotlin/io/libp2p/tools/protobuf/ProtobufUtils.kt: (35, 34): 'toByte(): Byte' is deprecated. Conversion of Char to Number is deprecated. Use Char.code property instead.
w: /home/jtraglia/git/jvm-libp2p/src/test/kotlin/io/libp2p/tools/protobuf/ProtobufUtils.kt: (36, 32): 'toByte(): Byte' is deprecated. Conversion of Char to Number is deprecated. Use Char.code property instead.
w: /home/jtraglia/git/jvm-libp2p/src/test/kotlin/io/libp2p/tools/protobuf/ProtobufUtils.kt: (40, 32): 'toByte(): Byte' is deprecated. Conversion of Char to Number is deprecated. Use Char.code property instead.

> Task :compileTestJava
Note: /home/jtraglia/git/jvm-libp2p/src/test/java/io/libp2p/tools/schedulers/Scheduler.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :test
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended

TcpTransportTest > dial then close server transport() FAILED
    org.opentest4j.AssertionFailedError: Connections not acknowledged by server ==> expected: <50> but was: <40>
        at app//org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
        at app//org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
        at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
        at app//org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:559)
        at app//io.libp2p.transport.TransportTests.connectClientAndServer(TransportTests.kt:74)
        at app//io.libp2p.transport.TransportTests.dial then close server transport(TransportTests.kt:162)
        at java.base@16.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base@16.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base@16.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base@16.0.1/java.lang.reflect.Method.invoke(Method.java:567)
        at app//org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
        at app//org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
        at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
        at app//org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
        at app//org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
        at app//org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
        at app//org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
        at app//org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
        at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
        at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
        at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
        at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
        at app//org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
        at app//org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
        at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
        at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
        at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
        at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
        at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
        at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at app//org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
        at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at java.base@16.0.1/java.util.ArrayList.forEach(ArrayList.java:1511)
        at app//org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
        at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
        at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at app//org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
        at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at java.base@16.0.1/java.util.ArrayList.forEach(ArrayList.java:1511)
        at app//org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
        at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
        at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at app//org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
        at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at app//org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
        at app//org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
        at app//org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
        at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
        at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
        at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
        at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
        at java.base@16.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base@16.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base@16.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base@16.0.1/java.lang.reflect.Method.invoke(Method.java:567)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
        at jdk.proxy1/jdk.proxy1.$Proxy2.stop(Unknown Source)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
        at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
        at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
        at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)

TcpTransportTest > dial then close client transport() FAILED
    org.opentest4j.AssertionFailedError: Connections not acknowledged by server ==> expected: <50> but was: <46>
        at app//org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
        at app//org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
        at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
        at app//org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:559)
        at app//io.libp2p.transport.TransportTests.connectClientAndServer(TransportTests.kt:74)
        at app//io.libp2p.transport.TransportTests.dial then close client transport(TransportTests.kt:148)
        at java.base@16.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base@16.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base@16.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base@16.0.1/java.lang.reflect.Method.invoke(Method.java:567)
        at app//org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
        at app//org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
        at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
        at app//org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
        at app//org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
        at app//org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
        at app//org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
        at app//org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
        at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
        at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
        at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
        at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
        at app//org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
        at app//org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
        at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
        at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
        at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
        at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
        at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
        at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at app//org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
        at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at java.base@16.0.1/java.util.ArrayList.forEach(ArrayList.java:1511)
        at app//org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
        at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
        at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at app//org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
        at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at java.base@16.0.1/java.util.ArrayList.forEach(ArrayList.java:1511)
        at app//org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
        at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
        at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at app//org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
        at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at app//org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
        at app//org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
        at app//org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
        at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
        at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
        at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
        at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
        at java.base@16.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base@16.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base@16.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base@16.0.1/java.lang.reflect.Method.invoke(Method.java:567)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
        at jdk.proxy1/jdk.proxy1.$Proxy2.stop(Unknown Source)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
        at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
        at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
        at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)

523 tests completed, 2 failed, 6 skipped

> Task :test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///home/jtraglia/git/jvm-libp2p/build/reports/tests/test/index.html

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 17s
16 actionable tasks: 13 executed, 3 up-to-date
```
</details>

**Comment by jtraglia** [comment]
So this is not a problem with ARM (aarch64) specifically. It's just that the timeout isn't long enough.

https://github.com/libp2p/jvm-libp2p/blob/511c5a2f03c8401f658be15667326fd5e9dc8168/src/test/kotlin/io/libp2p/transport/TransportTests.kt#L73-L75

When I change this sleep to 20 seconds, the build is successful. We should figure out a way to do without the sleep.

Note: 20 seconds was just a larger value. It might also work with 10 seconds, if we want a band-aid fix.

**Comment by ajsutton** [comment]
Ideally we'd use a waiter pattern here - basically keep retrying for up to something like 30 seconds for the assertions to pass. If they pass earlier than that the test can pass immediately so it takes the minimum amount of time.

**Comment by jtraglia** [comment]
Good idea. I'll submit a PR for that.

**Comment by jtraglia** [comment]
PR #221 fixed this issue.
