### ISSUE TITLE
Support dns4 multiaddrs

### ISSUE THREAD

**Issue by ajsutton** [libp2p/jvm-libp2p#70]
The Prysm Eth2 testnet uses a dns4 Multiaddr for it's bootstrap node which isn't currently supported by jvm-libp2p.

Multiaddr: `/dns4/prylabs.net/tcp/30001/p2p/16Uiu2HAm7Qwe19vz9WzD2Mxn7fXd1vgHHp4iccuyq7TxwRXoAGfc`

Error:
```
io.libp2p.core.Libp2pException: Missing IP4/IP6/DNSADDR in multiaddress /dns4/prylabs.net/tcp/30001/p2p/16Uiu2HAm7Qwe19vz9WzD2Mxn7fXd1vgHHp4iccuyq7TxwRXoAGfc

	at io.libp2p.transport.tcp.TcpTransport.fromMultiaddr(TcpTransport.kt:165)
	at io.libp2p.transport.tcp.TcpTransport.dial(TcpTransport.kt:129)
	at io.libp2p.network.NetworkImpl.connect(NetworkImpl.kt:77)
	at io.libp2p.core.Network$DefaultImpls.connect(Network.kt:55)
	at io.libp2p.network.NetworkImpl.connect(NetworkImpl.kt:15)
...
```

Would be good if jvm-libp2p supported this.

**Comment by jezhiggins** [comment]
I'll see if I can sort this out in the next couple of days.

**Comment by jezhiggins** [comment]
Going well - see feature/dns-resolver branch. Hopefully have it wrapped up sometime tomorrow.
